services:
  vessel_tracking_backend:
    build:
      context: ./backend
    container_name: vessel_tracking_backend
    image: vessel_tracking_backend
    environment:
      POSTGRES_DB: vessel_tracking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      FRONTEND_URL: https://www.quanlytauca.site
    command: >
      sh -c "
      python manage.py migrate &&
      python create_samples/main.py &&
      nohup python craete_samples/job.py > /dev/null 2>&1 &
      uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level info
      "
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    networks:
      - nginx_network
      - global_default


  vessel_tracking_frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: "https://backend.quanlytauca.site"
    image: vessel_tracking_frontend
    container_name: vessel_tracking_frontend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  global_default:
    external: true

volumes:
  backend_static:
  backend_media: