services:
  xoai_shop_backend:
    build:
      context: ./backend
    container_name: xoai_shop_backend
    image: xoai_shop_backend
    depends_on:
      xoai_shop_postgresql:
        condition: service_healthy
      xoai_shop_redis:
        condition: service_started
    environment:
      POSTGRES_DB: vessel_tracking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: 192.233.84.195
      POSTGRES_PORT: 5432
      FRONTEND_URL: https://www.quanlytauca.site
      REDIS_HOST: xoai_shop_redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 1
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn backend.wsgi --bind 0.0.0.0:8000 --workers 4 --access-logfile - --error-logfile -
      "
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    networks:
      - nginx_network

  xoai_shop_frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: "https://backend.quanlytauca.site"
    image: xoai_shop_frontend
    container_name: xoai_shop_frontend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  backend_static:
  backend_media: